"""phase5_checkins_and_qr_token_uses

Revision ID: 65ce1fba321e
Revises: 6847cb37d122
Create Date: 2026-08-25 03:14:40.167939

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '65ce1fba321e'
down_revision: str | Sequence[str] | None = '6847cb37d122'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_membership_id'), 'check_ins', ['membership_id'], unique=False)
    op.create_index('ix_check_ins_scanned_at', 'check_ins', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_check_ins_user_id'), 'check_ins', ['user_id'], unique=False)
    op.create_index('ix_check_ins_user_time', 'check_ins', ['user_id', 'scanned_at'], unique=False)
    op.create_table('qr_token_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('ix_qr_token_uses_used_at', 'qr_token_uses', ['used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qr_token_uses_used_at', table_name='qr_token_uses')
    op.drop_table('qr_token_uses')
    op.drop_index('ix_check_ins_user_time', table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_user_id'), table_name='check_ins')
    op.drop_index('ix_check_ins_scanned_at', table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_membership_id'), table_name='check_ins')
    op.drop_table('check_ins')
    # ### end Alembic commands ###
