"""phase4: payment columns and relationships

Revision ID: 6847cb37d122
Revises: 7dd8de8571c1
Create Date: 2026-08-25 02:16:40.628871

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6847cb37d122'
down_revision: str | Sequence[str] | None = '7dd8de8571c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_memberships_payment_id', 'memberships', 'payments', ['payment_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('payments', sa.Column('membership_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('external_id', sa.String(length=120), nullable=True))
    op.add_column('payments', sa.Column('method', sa.String(length=40), nullable=True))
    op.add_column('payments', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payments_membership_id'), 'payments', ['membership_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_unique_constraint(None, 'payments', ['external_id'])
    op.create_foreign_key(None, 'payments', 'memberships', ['membership_id'], ['id'], ondelete='SET NULL')
    op.drop_column('payments', 'reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('reference', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_membership_id'), table_name='payments')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'failure_reason')
    op.drop_column('payments', 'method')
    op.drop_column('payments', 'external_id')
    op.drop_column('payments', 'membership_id')
    op.drop_constraint('fk_memberships_payment_id', 'memberships', type_='foreignkey')
    # ### end Alembic commands ###
